---
title: "Data Import"
output: github_document
---

This file is for data imports.

# Load Packages
```{r}
library(tidyverse)
library(readxl)
library(haven)
```

## Load first data set:
```{r}
## Import litter df:
litters_df =
  read_csv(file = "data/FAS_litters.csv", 
           na = c('.', "NA", ""))

## Change column labels to snake case.
litters_df = janitor::clean_names(litters_df)
```

## Load second data set:
```{r}
## Import pups df:
pups_df =
  read_csv("data/FAS_pups.csv", 
           skip = 3, 
           na = c('.', "NA", ""))

## Change column labels to snake case.
pups_df = janitor::clean_names(pups_df)
```

## `select` some variables:

```{r}
litters_df |> 
  select(group, litter_number)

litters_df |> 
  select(group:gd_of_birth)

litters_df |> 
  select(-pups_survive)

litters_df |> 
  select(starts_with("gd"), group) # reorders columns

litters_df |> 
  select(GROUP = group, everything())
```

## Rename and relocate data
```{r}
litters_df |> 
  rename(GROUP = group)

litters_df |> 
  relocate(litter_number, gd0_weight) # Moves columns to the front of the DF.
```


## In the pups data select litter #, sex, and PD ears.
```{r}
pups_df |> 
  select(litter_number, sex, pd_ears)
```

## `filter` some rows:
```{r}
litters_df |> 
  filter(gd_of_birth == 20, pups_born_alive != 6, pups_born_alive < 10)

litters_df |> 
  filter(group %in% c("Con7", "Con8"))

litters_df |> 
  drop_na()

litters_df |> 
  drop_na(gd0_weight)
```

# In the pups data, keep only rows where PD walk is < 11 and sex is 2:
```{r}
pups_df |> 
  filter(pd_walk < 11, sex == 2)
```














